### PR TITLE
Impersonation logic the other way round

### PR DESCRIPTION
**Pull request by thegcat**
We think it would be more prudent to use the core logic to create a new session and then removing the bits not needed here, instead of trying to copy core logic into this plugin. Both approaches require to monitor the core logic across versions, but when using the core logic as proposed here you might have "too many" (security) features and not be missing a (security) feature that has not been ported to the plugin yet.

In addition, this PR ensures that nothing from the Admin session is carried over to the impersonated user (`reset_session`) to avoid any ill effects in the impersonated session.

### CODE REVIEW

**Comment by nounder** [comment]
When creating this plugin I aimed to make it compatible with 2.x and 3.x. Login logic was different across version so I had to re-implement it like this. After your awesome contribution it's time to drop 2.x support so people can get most of your work.

Can you please resolve conflicts for this pull request so I can merge it? For next few days I won't be able to do it on my own so I would appreciate your help.

**Comment by thegcat** [comment]
We hadn't thought of the 2.x compat, but if you're willing to drop support for it that's good too :-)

**Comment by thegcat** [comment]
I have updated (rebased) the PR, it should be mergeable now. Thank you!

**Comment by nounder** [comment]
Thanks to you :)

**Pull request merged**
